apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-logging
  namespace: logging
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd-logging
      serviceAccountName: fluentd-logging
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        imagePullPolicy: "Always"
        image: fluent/fluentd-kubernetes-daemonset:v1.13.3-debian-kafka-amd64-1.0
        #env:
        #  - name: FLUENT_KAFKA_BROKERS
        #    value: "192.168.2.239:9092"
        #  - name: FLUENT_UID
        #    value: '9000'
        #  - name: FLUENTD_SYSTEMD_CONF
        #    value: 'disable'
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
